--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/NetherPortal
branches:
- master
projects:
  NetherPortal:
    path: ""
    libs:
      - src: muqsit/simplepackethandler/SimplePacketHandler
        branch: pm5
        version: ^0.1.3
...
